mainapp/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from mainapp import apis, views

app_name = "mainapp"

router = SimpleRouter()
router.register("clients", apis.ClientViewSet, "apis-clients")
router.register("clients/phones", apis.PhoneNumberViewSet, "apis-clients-phones")
router.register("clients/addresses", apis.AddressViewSet, "apis-clients-addresses")
router.register("compositions", apis.CompositionViewSet, "apis-compositions")
router.register("orders", apis.OrderViewSet, "apis-orders")
router.register("orders/lines", apis.OrderLineViewSet, "apis-orders-lines")

urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),

    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),

    path("clients/list/", views.ClientListView.as_view(), name="clients-list"),
    path("clients/<int:pk>/delete/", views.ClientDeleteView.as_view(), name="client-delete"),
    path("clients/<int:pk>/details/", views.ClientDetailView.as_view(), name="client-details"),

    path("menus/create/", views.MenuCreateView.as_view(), name="menu-create"),
    path("menus/list/", views.MenuListView.as_view(), name="menus-list"),
    path("menus/<int:pk>/delete/", views.MenuDeleteView.as_view(), name="menu-delete"),
    path("menus/<int:pk>/details/", views.MenuDetailView.as_view(), name="menu-details"),
    path("menus/<int:pk>/update/", views.MenuUpdateView.as_view(), name="menu-update"),

    path("foods/create/", views.FoodCreateView.as_view(), name="food-create"),
    path("foods/list/", views.FoodListView.as_view(), name="foods-list"),
    path("foods/<int:pk>/delete/", views.FoodDeleteView.as_view(), name="food-delete"),
    path("foods/<int:pk>/details/", views.FoodDetailView.as_view(), name="food-details"),
    path("foods/<int:pk>/update/", views.FoodUpdateView.as_view(), name="food-update"),

    path("extras/create/", views.ExtraCreateView.as_view(), name="extra-create"),
    path("extras/list/", views.ExtraListView.as_view(), name="extras-list"),
    path("extras/<int:pk>/delete/", views.ExtraDeleteView.as_view(), name="extra-delete"),
    path("extras/<int:pk>/details/", views.ExtraDetailView.as_view(), name="extra-details"),
    path("extras/<int:pk>/update/", views.ExtraUpdateView.as_view(), name="extra-update"),

    path("orders/list/", views.OrderListView.as_view(), name="orders-list"),
    path("orders/<int:pk>/delete/", views.OrderDeleteView.as_view(), name="order-delete"),
    path("orders/<int:pk>/details/", views.OrderDetailView.as_view(), name="order-details"),
    path("orders/<int:pk>/update/", views.OrderUpdateView.as_view(), name="order-update"),

    path("apis/login/", apis.LoginApi.as_view()),
    path("apis/extras/", apis.ExtrasListView.as_view()),
    path("apis/menus/", apis.MenuListView.as_view()),
    path("apis/foods/", apis.FoodListView.as_view()),
    path("apis/cities/", apis.CityListView.as_view()),
    path("apis/", include(router.urls))
]

zetraiteur/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from zetraiteur import settings
from zetraiteur.settings import DEBUG

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Count
from django.utils.translation import gettext as _

# Create your models here.
from mainapp import ExtraType, OrderStatus


class ZeUser(User):
    username = None
    phone = models.CharField(max_length=255, unique=True)
    is_admin = models.BooleanField(default=False)
    is_deliveryman = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('first_name', 'last_name')

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Client(models.Model):
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    address = models.TextField(max_length=1000, verbose_name=_('Address'))
    city = models.ForeignKey('City', verbose_name=_('City'), related_name='Clients', on_delete=models.SET_NULL,
                             null=True)
    phone = models.CharField(max_length=255, unique=True, db_index=True)
    email = models.EmailField(null=True, blank=True)
    verified = models.BooleanField(default=False, verbose_name=_('Verified'))

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @property
    def orders_count(self) -> int:
        return self.orders.all().count()

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')
        ordering = ['id']


class PhoneNumber(models.Model):
    phone = models.CharField(max_length=255, unique=True, verbose_name=_('Phone Number'))
    client = models.ForeignKey('Client', verbose_name=_('Client'), on_delete=models.CASCADE, related_name='phones')

    class Meta:
        ordering = ('id',)
        verbose_name = _('Phone Number')
        verbose_name_plural = _('Phone Numbers')

    def __str__(self):
        return self.phone


class City(models.Model):
    name = models.CharField(verbose_name=_('Name'), max_length=255)
    delivery_fee = models.PositiveIntegerField(verbose_name=_('Delivery Fee'), default=0)

    class Meta:
        ordering = ('id',)
        verbose_name = _('City')
        verbose_name_plural = _('Cities')


class Address(models.Model):
    address = models.TextField(max_length=1000, verbose_name=_('Address'))
    client = models.ForeignKey('Client', verbose_name=_('Client'), on_delete=models.CASCADE, related_name='addresses')
    city = models.ForeignKey('City', verbose_name=_('City'), on_delete=models.SET_NULL, related_name='addresses',
                             null=True)

    class Meta:
        ordering = ('id',)
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def __str__(self):
        return self.address


class Menu(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('Name'))
    audio_file_name = models.CharField(max_length=255, verbose_name=_('Music'), blank=True)
    available = models.BooleanField(default=True, verbose_name=_('Available'))
    image = models.ImageField(upload_to="images", verbose_name=_('Image'), null=True, blank=True)
    font_name = models.CharField(max_length=255, blank=True, verbose_name=_('Font'))
    price = models.PositiveIntegerField(verbose_name=_('Price'), default=0, blank=True)

    class Meta:
        verbose_name = _('Menu')
        verbose_name_plural = _('Menus')
        ordering = ('name',)

    def __str__(self):
        return self.name


class Section(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    position = models.PositiveIntegerField(default=1, verbose_name=_('Position'))
    menu = models.ForeignKey('Menu', verbose_name=_('Menu'), on_delete=models.CASCADE, related_name="sections")

    class Meta:
        ordering = ('position',)
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')

    def __str__(self):
        return f"{self.menu} > {self.name}"


class Food(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    price = models.PositiveIntegerField(verbose_name=_('Price'), default=0)
    discount_price = models.PositiveIntegerField(verbose_name=_('Discount Price'), null=True, blank=True)
    description = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(upload_to="images", verbose_name=_('Image'), blank=True, null=True)
    section = models.ForeignKey('Section', verbose_name=_('Section'), on_delete=models.CASCADE, related_name="foods")

    @property
    def actual_price(self):
        if self.discount_price or self.discount_price != 0:
            return self.discount_price
        if self.price == 0:
            return self.section.menu.price
        return self.price

    class Meta:
        ordering = ('name', 'section__position')
        verbose_name = _('Food')
        verbose_name_plural = _('Foods')

    def __str__(self):
        return self.name


class Extra(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('Name'))
    type = models.CharField(max_length=20, choices=ExtraType.CHOICES, verbose_name=_('Type'), default=ExtraType.OTHER)
    price = models.PositiveIntegerField(verbose_name=_('Price'))
    discount_price = models.PositiveIntegerField(verbose_name=_('Discount Price'), null=True, blank=True)
    image = models.ImageField(upload_to="images", verbose_name=_('Image'), blank=True, null=True)

    @property
    def actual_price(self):
        if self.discount_price or self.discount_price != 0:
            return self.discount_price
        return self.price

    class Meta:
        ordering = ('name', 'type')
        verbose_name = _('Extra')
        verbose_name_plural = _('Extras')

    def __str__(self):
        return self.name


class Composition(models.Model):
    menu = models.ForeignKey('Menu', on_delete=models.CASCADE, verbose_name=_('Menu'))
    selected_foods = models.ManyToManyField('Food', through='CompositionFood', through_fields=('composition', 'food',),
                                            verbose_name=_('Selected Foods'), )
    extras = models.ManyToManyField('Extra', verbose_name=_('Extras'), related_name='compositions', )
    cost = models.PositiveIntegerField(verbose_name=_('Cost'), default=0)

    @property
    def actual_cost(self) -> int:
        cost = 0
        for food in self.selected_foods.all():
            cost += food.actual_price
        return cost

    def __str__(self):
        return "{}: {} + {} at {} DZD".format(self.menu,
                                              ", ".join([food.name for food in self.selected_foods.all()]),
                                              ", ".join([extra.name for extra in self.extras.all()]),
                                              self.cost)

    class Meta:
        verbose_name = _('Composition')
        verbose_name_plural = _('Compositions')
        ordering = ('-id',)


class CompositionFood(models.Model):
    food = models.ForeignKey('Food', verbose_name=_('Food'), on_delete=models.CASCADE)
    composition = models.ForeignKey('Composition', verbose_name=_('Composition'), on_delete=models.CASCADE)
    food_price = models.PositiveIntegerField(verbose_name=_('Food Price'), default=0)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.food_price = self.food.actual_price
        super(CompositionFood, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                          update_fields=update_fields)

    class Meta:
        ordering = ('food__section__position',)


class Order(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    number = models.CharField(unique=True, max_length=255)
    status = models.CharField(max_length=20, choices=OrderStatus.CHOICES, default=OrderStatus.PENDING)
    client = models.ForeignKey('Client', on_delete=models.CASCADE, related_name="orders", verbose_name=_('Client'))
    phone = models.ForeignKey('PhoneNumber', on_delete=models.CASCADE, related_name="orders", verbose_name=_('Phone'),
                              null=True, blank=True)
    address = models.ForeignKey('Address', on_delete=models.CASCADE, related_name="orders", verbose_name=_('Address'),
                                null=True, blank=True)

    @property
    def get_phone(self):
        return self.phone or self.client.phone

    @property
    def get_address(self):
        return self.address or self.client.address

    @property
    def items_count(self):
        return self.lines.annotate(count=Sum("quantity")).values("count").get('count', 0)

    @property
    def cost(self):
        cost = 0
        for line in self.lines.all():
            cost += line.total
        return cost

    @staticmethod
    def generate_number():
        from random import randint
        return randint(11111, 99999)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.number = self.generate_number()
        super(Order, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                update_fields=update_fields)

    def __str__(self):
        return self.number

    class Meta:
        ordering = ('-created_at',)
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')


class OrderLine(models.Model):
    composition = models.ForeignKey('Composition', on_delete=models.CASCADE, verbose_name=_('Composition'))
    quantity = models.PositiveIntegerField(verbose_name=_('Quantity'), default=1)

mainapp/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from mainapp.models import Menu, Section, Food, Extra, Order, OrderLine


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "palceholder": _('Username')
    }), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": _('Password')
    }), required=True)

    @property
    def get_username(self):
        return self.cleaned_data.get('username', "")

    @property
    def get_password(self):
        return self.cleaned_data.get('password', "")


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'image', 'price', 'available', 'audio_file_name', 'font_name')


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ('name', 'position', 'menu')


MenuWithSectionsFormSet = inlineformset_factory(Menu, Section, fields=('name', 'position',),
                                                extra=0, min_num=1, validate_min=True, max_num=3,
                                                validate_max=True)


class SectionsFormsetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SectionsFormsetHelper, self).__init__(*args, **kwargs)
        self.template = 'bootstrap4/table_inline_formset.html'


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ('name', 'description', 'image', 'price', 'discount_price', 'section')


class ExtraForm(forms.ModelForm):
    class Meta:
        model = Extra
        fields = ('name', 'type', 'image', 'price', 'discount_price')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('status',)


class OrderLineForm(forms.ModelForm):
    class Meta:
        model = OrderLine
        fields = ('composition', 'quantity')



class DeleteForm(forms.Form):
    pass

mainapp/templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE }}">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="decoration home accessories dz algeria">

    <!-- Title Page-->
    <title>{% trans "Dashboard" %}</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet"
          media="all">
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
          media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}"
          rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

    <!-- Jquery JS-->
    <script src={% static "vendor/jquery-3.2.1.min.js" %}></script>

    {% block styles %}

    {% endblock styles %}

</head>
<body class="animsition">

<div class="page-wrapper">
    <!-- HEADER MOBILE-->
    <header class="header-mobile d-block d-lg-none">
        <div class="header-mobile__bar">
            <div class="container-fluid">
                <div class="header-mobile-inner">
                    <a class="logo" href="index.html">
                        <img src="{% static 'images/icon/logo.png' %}" alt="CoolAdmin"/>
                    </a>
                    <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>
        <nav class="navbar-mobile">
            <div class="container-fluid">
                <ul class="navbar-mobile__list list-unstyled">
                    <li class="has-sub">
                        <a class="js-arrow" href="#">
                            <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                            <li>
                                <a href="index.html">Dashboard 1</a>
                            </li>
                            <li>
                                <a href="index2.html">Dashboard 2</a>
                            </li>
                            <li>
                                <a href="index3.html">Dashboard 3</a>
                            </li>
                            <li>
                                <a href="index4.html">Dashboard 4</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="chart.html">
                            <i class="fas fa-chart-bar"></i>Charts</a>
                    </li>
                    <li>
                        <a href="table.html">
                            <i class="fas fa-table"></i>Tables</a>
                    </li>
                    <li>
                        <a href="form.html">
                            <i class="far fa-check-square"></i>Forms</a>
                    </li>
                    <li>
                        <a href="calendar.html">
                            <i class="fas fa-calendar-alt"></i>Calendar</a>
                    </li>
                    <li>
                        <a href="map.html">
                            <i class="fas fa-map-marker-alt"></i>Maps</a>
                    </li>
                    <li class="has-sub">
                        <a class="js-arrow" href="#">
                            <i class="fas fa-copy"></i>Pages</a>
                        <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                            <li>
                                <a href="login.html">Login</a>
                            </li>
                            <li>
                                <a href="register.html">Register</a>
                            </li>
                            <li>
                                <a href="forget-pass.html">Forget Password</a>
                            </li>
                        </ul>
                    </li>
                    <li class="has-sub">
                        <a class="js-arrow" href="#">
                            <i class="fas fa-desktop"></i>UI Elements</a>
                        <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                            <li>
                                <a href="button.html">Button</a>
                            </li>
                            <li>
                                <a href="badge.html">Badges</a>
                            </li>
                            <li>
                                <a href="tab.html">Tabs</a>
                            </li>
                            <li>
                                <a href="card.html">Cards</a>
                            </li>
                            <li>
                                <a href="alert.html">Alerts</a>
                            </li>
                            <li>
                                <a href="progress-bar.html">Progress Bars</a>
                            </li>
                            <li>
                                <a href="modal.html">Modals</a>
                            </li>
                            <li>
                                <a href="switch.html">Switchs</a>
                            </li>
                            <li>
                                <a href="grid.html">Grids</a>
                            </li>
                            <li>
                                <a href="fontawesome.html">Fontawesome Icon</a>
                            </li>
                            <li>
                                <a href="typo.html">Typography</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- END HEADER MOBILE-->

    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
        <div class="logo">
            <a href="#">
                <img src="{% static 'images/icon/logo.png' %}" alt="Cool Admin"/>
            </a>
        </div>
        <div class="menu-sidebar__content js-scrollbar1">
            <nav class="navbar-sidebar">
                <ul class="list-unstyled navbar__list">
                    <li>
                        <a href="{% url "mainapp:dashboard" %}">{% trans 'Dashboard' %}</a>
                    </li>
                    <li>
                        <a href="#">{% trans 'Users' %}</a>
                    </li>
                    <li>
                        <a href="{% url "mainapp:clients-list" %}">{% trans 'Clients' %}</a>
                    </li>
                    <li>
                        <a href="{% url "mainapp:menus-list" %}">{% trans 'Menus' %}</a>
                    </li>
                    <li>
                        <a href="{% url "mainapp:foods-list" %}">{% trans 'Food' %}</a>
                    </li>
                    <li>
                        <a href="{% url "mainapp:extras-list" %}">{% trans 'Extra' %}</a>
                    </li>
                    <li>
                        <a href="{% url "mainapp:orders-list" %}">{% trans 'Orders' %}</a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
    <!-- END MENU SIDEBAR-->

    <!-- PAGE CONTAINER-->
    <div class="page-container">
        <!-- HEADER DESKTOP-->
        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <form class="form-header" action="" method="POST">

                        </form>
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="account-item clearfix js-item-menu">
                                    <div class="image">
                                        <img src="{% static 'images/icon/avatar-01.jpg' %}" alt="profile image"/>
                                    </div>
                                    <div class="content">
                                        <a class="js-acc-btn" href="#">{{ user.first_name }}</a>
                                    </div>
                                    <div class="account-dropdown js-dropdown">
                                        <div class="info clearfix">
                                            <div class="image">
                                                <a href="#">
                                                    <img src="{% static 'images/icon/avatar-01.jpg' %}"
                                                         alt="John Doe"/>
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h5 class="name">
                                                    <a href="#">{{ user.full_name }}</a>
                                                </h5>
                                                <span class="email">{{ user.email }}</span>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__body">
                                            <div class="account-dropdown__item">
                                                <a href="{% comment %}{% url 'accounts:profile-details' user.id %}{% endcomment %}">
                                                    <i class="zmdi zmdi-account"></i>{% trans "Account" %}</a>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__footer">
                                            <a href="{% url 'mainapp:logout' %}">
                                                <i class="zmdi zmdi-power"></i>{% trans "Logout" %}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- HEADER DESKTOP-->

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock content %}
                </div>
            </div>
        </div>

        {% block modals %}
        {% endblock modals %}
        <!-- END MAIN CONTENT-->
        <!-- END PAGE CONTAINER-->
    </div>

</div>

<!-- Bootstrap JS-->
<script src={% static "vendor/bootstrap-4.1/popper.min.js" %}></script>
<script src={% static "vendor/bootstrap-4.1/bootstrap.min.js" %}></script>
<!-- Vendor JS       -->
<script src={% static "vendor/slick/slick.min.js" %}></script>
<script src={% static "vendor/wow/wow.min.js" %}></script>
<script src={% static "vendor/animsition/animsition.min.js" %}></script>
<script src={% static "vendor/bootstrap-progressbar/bootstrap-progressbar.min.js" %}></script>
<script src={% static "vendor/counter-up/jquery.waypoints.min.js" %}></script>
<script src={% static "vendor/counter-up/jquery.counterup.min.js" %}></script>
<script src={% static "vendor/circle-progress/circle-progress.min.js" %}></script>
<script src={% static "vendor/perfect-scrollbar/perfect-scrollbar.js" %}></script>
<script src={% static "vendor/chartjs/Chart.bundle.min.js" %}></script>
<script src={% static "vendor/select2/select2.min.js" %}></script>

<!-- Main JS-->
<script src={% static "js/main.js" %}></script>

{% block scripts %}
{% endblock scripts %}

</body>
</html>

mainapp/templates/dashboard/delete_client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mainapp/templates/dashboard/order_details.html
{% extends 'dashboard/base.html' %}
{% load i18n %}


{% block content %}
    <h3 class="title-5 m-b-35">{% trans "Order Details" %}</h3>
    <div class="ml-4">
        <h4>{% trans 'Order Number' %}: {{ order.number }}</h4>
        <hr>
        <h4>{% trans 'Date' %}: {{ order.created_at }}</h4>
        <hr>
        <div class="row flex-row">
            <h4 class="col-md-4 col-sm-4 col-12">{% trans 'Status' %}: {{ order.get_status_display }}</h4>
            <select name="status" id="status-select" class="col-md-4 col-sm-4 col-12">
                <option value="test">test</option>
                <option value="test">test</option>
                <option value="test">test</option>
            </select>
        </div>
        <hr>
        <h4>{% trans 'Client' %}: {{ order.client }}</h4>
        <hr>
        <h4>{% trans 'phone' %}: {{ order.get_phone }}</h4>
        <hr>
        <h4>{% trans 'address' %}: {{ order.get_address }}</h4>
        <hr>
        <h4>{% trans 'cost' %}: {{ order.cost }}</h4>
    </div>
    <div class="mb-3"></div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>{% trans 'Menu' %}</th>
                <th>{% trans 'Main' %}</th>
                <th>{% trans 'Extra' %}</th>
                <th>{% trans 'Quantity' %}</th>
                <th>{% trans 'total' %}</th>
            </tr>
            </thead>
            {% for line in order.lines.all %}
                <tr>
                    <td>{{ line.composition.menu }}</td>
                    <td>{% for food in line.composition.selected_foods.all %}
                        {{ food }},
                    {% endfor %}
                    </td>
                    <td>
                        {% for extra in line.composition.extras.all %}
                            {{ extra }},
                        {% endfor %}
                    </td>
                    <td>{{ line.quantity }}</td>
                    <td>{{ line.total }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
{% endblock %}