mainapp/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from mainapp import apis, views

app_name = "mainapp"

router = SimpleRouter()
router.register("clients", apis.ClientViewSet, "apis-clients")
router.register("clients/phones", apis.PhoneNumberViewSet, "apis-clients-phones")
router.register("clients/addresses", apis.AddressViewSet, "apis-clients-addresses")
router.register("compositions", apis.CompositionViewSet, "apis-compositions")
router.register("orders", apis.OrderViewSet, "apis-orders")
router.register("orders/lines", apis.OrderLineViewSet, "apis-orders-lines")

urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),

    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),

    path("clients/list/", views.ClientListView.as_view(), name="clients-list"),
    path("clients/<int:pk>/delete/", views.ClientDeleteView.as_view(), name="client-delete"),
    path("clients/<int:pk>/details/", views.ClientDetailView.as_view(), name="client-details"),

    path("menus/create/", views.MenuCreateView.as_view(), name="menu-create"),
    path("menus/list/", views.MenuListView.as_view(), name="menus-list"),
    path("menus/<int:pk>/delete/", views.MenuDeleteView.as_view(), name="menu-delete"),
    path("menus/<int:pk>/details/", views.MenuDetailView.as_view(), name="menu-details"),
    path("menus/<int:pk>/update/", views.MenuUpdateView.as_view(), name="menu-update"),

    path("foods/create/", views.FoodCreateView.as_view(), name="food-create"),
    path("foods/list/", views.FoodListView.as_view(), name="foods-list"),
    path("foods/<int:pk>/delete/", views.FoodDeleteView.as_view(), name="food-delete"),
    path("foods/<int:pk>/details/", views.FoodDetailView.as_view(), name="food-details"),
    path("foods/<int:pk>/update/", views.FoodUpdateView.as_view(), name="food-update"),

    path("extras/create/", views.ExtraCreateView.as_view(), name="extra-create"),
    path("extras/list/", views.ExtraListView.as_view(), name="extras-list"),
    path("extras/<int:pk>/delete/", views.ExtraDeleteView.as_view(), name="extra-delete"),
    path("extras/<int:pk>/details/", views.ExtraDetailView.as_view(), name="extra-details"),
    path("extras/<int:pk>/update/", views.ExtraUpdateView.as_view(), name="extra-update"),

    path("orders/list/", views.OrderListView.as_view(), name="orders-list"),
    path("orders/<int:pk>/delete/", views.OrderDeleteView.as_view(), name="order-delete"),
    path("orders/<int:pk>/details/", views.OrderDetailView.as_view(), name="order-details"),
    path("orders/<int:pk>/update/", views.OrderUpdateView.as_view(), name="order-update"),

    path("apis/login/", apis.LoginApi.as_view()),
    path("apis/extras/", apis.ExtrasListView.as_view()),
    path("apis/menus/", apis.MenuListView.as_view()),
    path("apis/foods/", apis.FoodListView.as_view()),
    path("apis/cities/", apis.CityListView.as_view()),
    path("apis/", include(router.urls))
]

zetraiteur/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from zetraiteur import settings
from zetraiteur.settings import DEBUG

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from mainapp.models import Menu, Section, Food, Extra, Order, OrderLine


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "palceholder": _('Username')
    }), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": _('Password')
    }), required=True)

    @property
    def get_username(self):
        return self.cleaned_data.get('username', "")

    @property
    def get_password(self):
        return self.cleaned_data.get('password', "")


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'image', 'price', 'available', 'audio_file_name', 'font_name')


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ('name', 'position', 'menu')


MenuWithSectionsFormSet = inlineformset_factory(Menu, Section, fields=('name', 'position',),
                                                extra=0, min_num=1, validate_min=True, max_num=3,
                                                validate_max=True)


class SectionsFormsetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SectionsFormsetHelper, self).__init__(*args, **kwargs)
        self.template = 'bootstrap4/table_inline_formset.html'


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ('name', 'description', 'image', 'price', 'discount_price', 'section')


class ExtraForm(forms.ModelForm):
    class Meta:
        model = Extra
        fields = ('name', 'type', 'image', 'price', 'discount_price')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('status',)


class OrderLineForm(forms.ModelForm):
    class Meta:
        model = OrderLine
        fields = ('composition', 'quantity')



class DeleteForm(forms.Form):
    pass

mainapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView, FormView
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from mainapp.filters import ClientFilter, MenuFilter, FoodFilter, ExtraFilter, OrderFilter
from mainapp.forms import LoginForm, DeleteForm, MenuForm, MenuWithSectionsFormSet, SectionsFormsetHelper, FoodForm, \
    ExtraForm
from mainapp.models import Client, Menu, Food, Extra, Order
from mainapp.tables import ClientTable, MenuTable, FoodTable, ExtraTable, OrderTable


class LoginView(FormView):
    form_class = LoginForm
    template_name = "dashboard/login.html"
    success_url = reverse_lazy("mainapp:dashboard")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('mainapp:dashboard')
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form: LoginForm):
        user = authenticate(self.request, username=form.get_username, password=form.get_password)
        if user:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            form.add_error("", _('Invalid Username or Password'))
            return self.form_invalid(form=form)


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("mainapp:login"))


@method_decorator(login_required, name="dispatch")
class Dashboard(TemplateView):
    template_name = "dashboard/index.html"


@method_decorator(login_required, name="dispatch")
class UsersListView(ListView):
    pass


@method_decorator(login_required, name="dispatch")
class UserCreateView(CreateView):
    pass


@method_decorator(login_required, name="dispatch")
class UserUpdateView(UpdateView):
    pass


@method_decorator(login_required, name="dispatch")
class UserDeleteView(DeleteView):
    pass


@method_decorator(login_required, name="dispatch")
class UserDetailView(DetailView):
    pass


@method_decorator(login_required, name="dispatch")
class ClientListView(SingleTableMixin, FilterView):
    model = Client
    table_class = ClientTable
    template_name = "dashboard/client_list.html"
    paginate_by = 25
    paginate_orphans = True
    allow_empty = True
    filterset_class = ClientFilter


@method_decorator(login_required, name="dispatch")
class ClientUpdateView(ListView):
    pass


@method_decorator(login_required, name="dispatch")
class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy("mainapp:clients-list")
    template_name = "dashboard/fragments/delete_form.html"
    form_class = DeleteForm

    def get_form(self):
        return self.form_class()

    def get_delete_url(self):
        return reverse("mainapp:client-delete", kwargs={"pk": self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        return super(ClientDeleteView, self).get_context_data(form=self.get_form(), delete_url=self.get_delete_url(),
                                                              **kwargs)

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.template_name, context, self.request)
            return JsonResponse(html, safe=False)
        return super(ClientDeleteView, self).render_to_response(context, **response_kwargs)


@method_decorator(login_required, name="dispatch")
class ClientDetailView(DetailView):
    template_name = "dashboard/fragments/client_profile.html"
    ajax_template_name = "dashboard/fragments/client_profile.html"
    context_object_name = "client"
    model = Client

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.ajax_template_name, context, self.request)
            return JsonResponse(html, safe=False)
        return super(ClientDetailView, self).render_to_response(context, **response_kwargs)


@method_decorator(login_required, name="dispatch")
class MenuListView(SingleTableMixin, FilterView):
    model = Menu
    table_class = MenuTable
    template_name = "dashboard/menu_list.html"
    paginate_by = 25
    paginate_orphans = True
    allow_empty = True
    filterset_class = MenuFilter


@method_decorator(login_required, name="dispatch")
class MenuCreateView(CreateView):
    model = Menu
    form_class = MenuForm
    formset_class = MenuWithSectionsFormSet
    template_name = "dashboard/fragments/create_menu_form.html"
    success_url = reverse_lazy("mainapp:menus-list")

    def get_form(self, form_class=None):
        self.formset = self.formset_class(**self.get_form_kwargs())
        return super(MenuCreateView, self).get_form(form_class=form_class)

    def get_context_data(self, **kwargs):
        context = super(MenuCreateView, self).get_context_data(**kwargs)
        context['formset'] = self.formset
        context['helper'] = SectionsFormsetHelper()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid() and self.formset.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        if form.is_valid():
            with transaction.atomic():
                self.object = form.save()
                self.formset.instance = self.object
                self.formset.save()

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, formset=self.formset))

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.template_name, context, self.request)
            return JsonResponse(html, safe=False)
        return super(MenuCreateView, self).render_to_response(context, **response_kwargs)


@method_decorator(login_required, name="dispatch")
class MenuUpdateView(UpdateView):
    model = Menu
    form_class = MenuForm
    formset_class = MenuWithSectionsFormSet
    template_name = "dashboard/fragments/create_menu_form.html"
    success_url = reverse_lazy("mainapp:menus-list")

    def get_form(self, form_class=None):
        self.formset = self.formset_class(**self.get_form_kwargs())
        return super(MenuUpdateView, self).get_form(form_class=form_class)

    def get_context_data(self, **kwargs):
        context = super(MenuUpdateView, self).get_context_data(**kwargs)
        context['formset'] = self.formset
        context['helper'] = SectionsFormsetHelper()
        context['url'] = reverse_lazy("mainapp:menu-update", kwargs={"pk": self.kwargs.get('pk')})
        return context

    def form_valid(self, form):
        if form.is_valid():
            with transaction.atomic():
                self.object = form.save()
                self.formset.instance = self.object
                self.formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid() and self.formset.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, formset=self.formset))

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.template_name, context, self.request)
            return JsonResponse(html, safe=False)
        return super(MenuUpdateView, self).render_to_response(context, **response_kwargs)


@method_decorator(login_required, name="dispatch")
class MenuDeleteView(DeleteView):
    model = Menu
    success_url = reverse_lazy("mainapp:menus-list")
    template_name = "dashboard/fragments/delete_form.html"
    form_class = DeleteForm

    def get_form(self):
        return self.form_class()

    def get_delete_url(self):
        return reverse("mainapp:menu-delete", kwargs={"pk": self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        return super(MenuDeleteView, self).get_context_data(form=self.get_form(), delete_url=self.get_delete_url(),
                                                            **kwargs)

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            html = render_to_string(self.template_name, context, self.request)
            return JsonResponse(html, safe=False)
        return super(MenuDeleteView, self).render_to_response(context, **response_kwargs)


@method_decorator(login_required, name="dispatch")
class MenuDetailView(DetailView):
    pass


@method_decorator(login_required, name="dispatch")
class FoodListView(SingleTableMixin, FilterView):
    model = Food
    table_class = FoodTable
    template_name = "dashboard/food_list.html"
    paginate_by = 25
    paginate_orphans = True
    allow_empty = True
    filterset_class = FoodFilter


@method_decorator(login_required, name="dispatch")
class FoodCreateView(CreateView):
    model = Food
    form_class = FoodForm
    template_name = "dashboard/fragments/create_food_form.html"
    success_url = reverse_lazy("mainapp:foods-list")

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():

mainapp/templates/dashboard/fragments/client_profile.html
{% load i18n %}
<div class="">
    <div class="card">
        <div class="card-header">
            <i class="fa fa-user"></i>
            <strong class="card-title pl-2">{% trans "Client Details" %}</strong>
        </div>
        <div class="card-body">
            <div class="mx-auto d-block">
                <h5 class="text-sm-center mt-2 mb-1"><i class="fa fa-user-circle"></i> {{ client.full_name }}
                    {% if client.verified %}
                        <i class="fa fa-check"></i>
                    {% else %}
                        <i class="fa fa-close"></i>
                    {% endif %}  </h5>
                <hr>
                <h5 class="text-sm-center mt-2 mb-1"><i class="fa fa-inbox"></i> {{ client.email|default:"_" }}</h5>
                <hr>
                <div class="location text-sm-center">
                    <i class="fa fa-map-marker"></i> {{ client.address }}
                    {% for address in client.addresses.all %}
                        <i class="fa fa-map-marker"></i> {{ address }}
                    {% endfor %}
                </div>
                <hr>
                <div class="location text-sm-center">
                    <i class="fa fa-phone"></i> {{ client.phone }}
                    {% for phone in client.phones.all %}
                        <i class="fa fa-map-marker"></i> {{ phone }}
                    {% endfor %}
                </div>
                <hr>
                <div class="location text-sm-center">
                    <i class="zmdi zmdi-pizza">&nbsp;</i>{{ client.orders_count }}
                </div>
            </div>
        </div>
    </div>
</div>

mainapp/templates/dashboard/fragments/create_extra_form.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

<form id="create-extra-form" action="{% if not url %}{% url 'mainapp:extra-create' %}{% else %}{{ url }}{% endif %}"
      method="POST" enctype="multipart/form-data" class="p-1">
    {% csrf_token %}
    {% trans 'Create Food' as title %}
    {% include "dashboard/fragments/modal_title.html" with title=title %}
    {{ form|crispy }}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"> {% trans 'Cancel' %}</button>
        <button type="submit" class="btn btn-primary"
                onclick="$('#create-extra-form').submit()">{% if not url %}
            {% trans 'Create' %}
        {% else %}
            {% trans 'Update' %}
        {% endif %}  </button>
    </div>
</form>

mainapp/templates/dashboard/fragments/create_food_form.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

<form id="create-food-form" action="{% if not url %}{% url 'mainapp:food-create' %}{% else %}{{ url }}{% endif %}"
      method="POST" enctype="multipart/form-data" class="p-1">
    {% csrf_token %}
    {% trans 'Create Food' as title %}
    {% include "dashboard/fragments/modal_title.html" with title=title %}
    {{ form|crispy }}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"> {% trans 'Cancel' %}</button>
        <button type="submit" class="btn btn-primary"
                onclick="$('#create-food-form').submit()">{% if not url %}
            {% trans 'Create' %}
        {% else %}
            {% trans 'Update' %}
        {% endif %}  </button>
    </div>
</form>

mainapp/templates/dashboard/fragments/create_menu_form.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

<form id="create-menu-form" action="{% if not url %}{% url 'mainapp:menu-create' %}{% else %}{{ url }}{% endif %}"
      method="POST" enctype="multipart/form-data" class="p-1">
    {% csrf_token %}
    {% trans 'Create Menu' as title %}
    {% include "dashboard/fragments/modal_title.html" with title=title %}
    {{ form|crispy }}
    <h3>{% trans 'Sections' %}</h3>
    {% crispy formset helper %}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"> {% trans 'Cancel' %}</button>
        <button type="submit" class="btn btn-primary"
                onclick="$('#create-menu-form').submit()">{% if not url %}
            {% trans 'Create' %}
        {% else %}
            {% trans 'Update' %}
        {% endif %}  </button>
    </div>
</form>


<script type="text/javascript">
    $('tr').formset({
        addText: '<i class="fas fa-plus" style="color: #0b0b0b"></i> <span style="color: #0b0b0b">{% trans 'Add' %}</span>',
        deleteText: '<i class="fas fa-trash" style="color: #0b0b0b"></i>',
        prefix: '{{ formset.prefix }}'
    })
</script>

mainapp/templates/dashboard/fragments/delete_form.html
{% load i18n %}
{% load bootstrap4 %}
<form action="{{ delete_url }}" method="post" class="form">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title" id="scrollmodalLabel">{% trans 'Delete ' %}{{ object }}{% trans "?" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"> {% trans 'Cancel' %}</button>
        {% trans 'Delete' as delete %}
        {% bootstrap_button delete %}
    </div>
</form>

mainapp/templates/dashboard/fragments/modal_title.html
<div class="modal-header">
    <h5 class="modal-title" id="scrollmodalLabel">{{ title|default:"" }}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

mainapp/templates/dashboard/fragments/update_order_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>